name: phallet

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  issues:
    types: [ opened, reopened, closed ]

jobs:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies 
      run: conda config --add channels defaults
           conda config --add channels conda-forge 
           conda config --add channels bioconda
           conda env create --file dependencies.yaml
    - name: Checkout
      uses: actions/checkout@v3
    - name: Running phallet
      run: bash phallet.sh
    - name: LS Output after checkout 
      run: ls