name: phallet

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  issues:
    types: [ opened, reopened, closed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: echo $SUPER_SECRET
    - name: Checkout
      uses: actions/checkout@v3
      shell: bash

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild
        bash dependencies.sh
        bash phallet.sh

    - name: Build
      run: gprbuild -j0 -p