name: phallet 

on: 
  push: 
      branches: 
      - main
  pull_request:
      branches:
      - main
jobs: 
  test:
    name: phallet_setup
    runs-on: ${{matrix.os}}
    strategy: 
      fail-fast: false
      matrix: 
        os: ["ubuntu-latest","macos-latest","windows-latests"]
        python-version: ["3.7","3.11"]
  steps: 
    -uses: conda-incubator/setup-miniconda@v3
     with:
       auto-update-conda: true
       python-version:${{matrix.python-version}}
    -name: Conda info
     shell: bash -el {0}
     run: conda info
    -name: Conda list
     shell: pwsh
     run: conda list
    -name: Set up the different conda channels 
     run: conda config --add channels defaults 
          conda config --add channels conda-forge   
          conda config --add channels bioconda
          bash dependencies.sh
    -name: Run phallet by default 
     run: bash phallet.sh 

    

    
    
