name: phallet 

on: 
  push: 
      branches: 
      - main
  pull_request:
      branches:
      - main
jobs: 
  test:
    name: phallet_setup
    runs-on: ${{matrix.os}}
    strategy: 
      fail-fast: false
      matrix: 
        version: 
          - "nightly"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
  steps: 
    -uses: actions/checkout@v4
    -name: Install dependencies (Conda install) 
     run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/ miniconda3/miniconda.sh 
          bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 
          rm -rf ~/miniconda3/miniconda.sh ~/miniconda3/bin/conda init bash
    -name: Set up the different conda channels 
     run: conda config --add channels defaults 
          conda config --add channels conda-forge   
          conda config --add channels bioconda
          bash dependencies.sh
    -name: Run phallet by default 
     run: bash phallet.sh 

    

    
    
